### ISSUE TITLE
Ingredients re spawning at incorrect sizes

### ISSUE THREAD

**Issue by cseyz** [Porkins97/DinoNuggetsGame#17]
Placing an ingredient into the bin before it re spawns on the table causes it to re spawn at half of its original size.

When you place an ingredient over the bin it scales down so that you can see it falling into the bin - I think its saving this transform to the prefab somehow.

**Comment by Porkins97** [comment]
In addition to this, instantiated copies keep some weird values from the object they replace. For instance, throwing a chopping board on the oven before the next object spawns causes the clone to spawn on fire and non interactable
