### ISSUE TITLE
If a player picks up a pot from the stove they are unable to place it back down.

### ISSUE THREAD

**Issue by cseyz** [Porkins97/DinoNuggetsGame#30]

**Comment by cseyz** [comment]
Without the pot on the stove you are unable to play the game - So maybe we just disable the pot from being picked up for now?

**Comment by jaronwilding** [comment]
Issue fix script : Stove.cs

Issue was that it would try to get the component of "CapsuleCollider", when it was changed to a "Box Collider" later down the track, and the script wasn't updated to follow along.
Also added: Stove_Collider.cs
Added a check to see if object is a pot or pan, and if so, place them. This means that other utensils (except for burnables) cannot be placed.
