### ISSUE TITLE
Textures get lost when in fire

### ISSUE THREAD

**Issue by jaronwilding** [Porkins97/DinoNuggetsGame#37]
Objects lose their materials when a fire is close by.

**Comment by Porkins97** [comment]
This is a feature. The ingredients are burnt

**Comment by jaronwilding** [comment]
Maybe, but it feels like they should fade to a different material, say a burnt material, instead of just going the default.

**Comment by cseyz** [comment]
It should keep the same texture - it just darkens the material when they are burned. I haven't seen any problem with it yet - is there anything you can do to recreate it and take a screenshot?
